// <auto-generated />
using System;
using LentSoft.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LentSoft.Web.Migrations
{
    [DbContext(typeof(LentSoftDbContext))]
    [Migration("20260722202211_UpdateRolesConstraint")]
    partial class UpdateRolesConstraint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LentSoft.Web.Models.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("pendiente");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Servicio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaHora");

                    b.HasIndex("UserId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estado = "confirmada",
                            FechaCreacion = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaHora = new DateTime(2026, 5, 25, 10, 0, 0, 0, DateTimeKind.Utc),
                            Servicio = "Examen de vista",
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Estado = "pendiente",
                            FechaCreacion = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaHora = new DateTime(2026, 6, 2, 14, 30, 0, 0, DateTimeKind.Utc),
                            Servicio = "Ajuste de lentes",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaContratacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Puesto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Salario")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Activo");

                    b.HasIndex("Departamento");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Departamento = "Atención al Cliente",
                            Email = "maria.garcia@lentsoft.com",
                            FechaContratacion = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "María García",
                            Puesto = "Optometrista",
                            Salario = 25000.00m,
                            Telefono = "555-0101"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Departamento = "Ventas",
                            Email = "juan.perez@lentsoft.com",
                            FechaContratacion = new DateTime(2025, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Juan Pérez",
                            Puesto = "Vendedor",
                            Salario = 18000.00m,
                            Telefono = "555-0102"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Departamento = "Administración",
                            Email = "ana.martinez@lentsoft.com",
                            FechaContratacion = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Ana Martínez",
                            Puesto = "Gerente",
                            Salario = 35000.00m,
                            Telefono = "555-0103"
                        });
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("pendiente");

                    b.Property<DateTime>("FechaEmision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Impuestos")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("MetodoPago")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("NumeroFactura")
                        .IsUnique();

                    b.HasIndex("OrderId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DireccionEnvio")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("pendiente");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaPedido")
                        .IsDescending();

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DireccionEnvio = "Calle 123 #45-67",
                            Estado = "entregado",
                            FechaPedido = new DateTime(2026, 5, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            Total = 2500.00m,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            DireccionEnvio = "Calle 123 #45-67",
                            Estado = "enviado",
                            FechaPedido = new DateTime(2026, 5, 20, 14, 30, 0, 0, DateTimeKind.Utc),
                            Total = 1800.00m,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cantidad = 1,
                            OrderId = 1,
                            PrecioUnitario = 2500.00m,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            Cantidad = 1,
                            OrderId = 2,
                            PrecioUnitario = 1800.00m,
                            ProductId = 3
                        });
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Marca")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("PrecioDescuento")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("Activo");

                    b.HasIndex("Categoria");

                    b.HasIndex("Nombre");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Categoria = "lentes-sol",
                            Descripcion = "Lentes de sol clásicos estilo aviador",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImagenUrl = "https://images.unsplash.com/photo-1572635196237-14b3f281503f",
                            Marca = "Ray-Ban",
                            Nombre = "Lentes Ray-Ban Aviator",
                            Precio = 2500.00m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Categoria = "lentes-contacto",
                            Descripcion = "Lentes de contacto mensuales",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Marca = "Acuvue",
                            Nombre = "Lentes de Contacto Acuvue",
                            Precio = 450.00m,
                            PrecioDescuento = 399.00m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Categoria = "monturas",
                            Descripcion = "Montura deportiva ultraligera",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Marca = "Oakley",
                            Nombre = "Montura Oakley Sport",
                            Precio = 1800.00m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Categoria = "lentes-graduados",
                            Descripcion = "Lentes graduados con diseño clásico",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Marca = "LentSoft",
                            Nombre = "Lentes Graduados Classic",
                            Precio = 1200.00m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Categoria = "accesorios",
                            Descripcion = "Estuche rígido para lentes",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Marca = "LentSoft",
                            Nombre = "Estuche Premium",
                            Precio = 150.00m,
                            PrecioDescuento = 99.00m,
                            Stock = 200
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Categoria = "accesorios",
                            Descripcion = "Solución limpiadora para lentes 360ml",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Marca = "Opti-Free",
                            Nombre = "Líquido Limpiador",
                            Precio = 120.00m,
                            Stock = 150
                        });
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("usuario");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UltimaCompra")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Role");

                    b.ToTable("Users", t =>
                        {
                            t.HasCheckConstraint("CK_Users_Role", "[Role] IN ('usuario', 'admin', 'optometra', 'ventas')");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@lentsoft.com",
                            FechaRegistro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Administrador",
                            PasswordHash = "$2a$11$MJPUqK7jAM6tEvUkExo1cO/3cmh4MpxnXNVPg./4kKzlsqAwPW/oq",
                            Role = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "user@lentsoft.com",
                            FechaRegistro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Usuario Demo",
                            PasswordHash = "$2a$11$q43GcbtmtTn9FyysOC73SO4HUFfBAF43GzPuZ6y0d0EZeDitCKqGa",
                            Role = "usuario"
                        });
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.Appointment", b =>
                {
                    b.HasOne("LentSoft.Web.Models.Entities.User", "User")
                        .WithMany("Appointments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.Invoice", b =>
                {
                    b.HasOne("LentSoft.Web.Models.Entities.Order", "Order")
                        .WithMany("Invoices")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.Order", b =>
                {
                    b.HasOne("LentSoft.Web.Models.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.OrderItem", b =>
                {
                    b.HasOne("LentSoft.Web.Models.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LentSoft.Web.Models.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.Order", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.Product", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.User", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
