// <auto-generated />
using System;
using LentSoft.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LentSoft.Web.Migrations
{
    [DbContext(typeof(LentSoftDbContext))]
    partial class LentSoftDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LentSoft.Web.Models.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("pendiente");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Servicio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaHora");

                    b.HasIndex("UserId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estado = "confirmada",
                            FechaCreacion = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaHora = new DateTime(2026, 5, 25, 10, 0, 0, 0, DateTimeKind.Utc),
                            Servicio = "Examen de vista",
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Estado = "pendiente",
                            FechaCreacion = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaHora = new DateTime(2026, 6, 2, 14, 30, 0, 0, DateTimeKind.Utc),
                            Servicio = "Ajuste de lentes",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Gafas"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Lentes"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Accesorios"
                        });
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaContratacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Puesto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Salario")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Activo");

                    b.HasIndex("Departamento");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Departamento = "Atención al Cliente",
                            Email = "maria.garcia@lentsoft.com",
                            FechaContratacion = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "María García",
                            Puesto = "Optometrista",
                            Salario = 25000.00m,
                            Telefono = "555-0101"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Departamento = "Ventas",
                            Email = "juan.perez@lentsoft.com",
                            FechaContratacion = new DateTime(2025, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Juan Pérez",
                            Puesto = "Vendedor",
                            Salario = 18000.00m,
                            Telefono = "555-0102"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Departamento = "Administración",
                            Email = "ana.martinez@lentsoft.com",
                            FechaContratacion = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Ana Martínez",
                            Puesto = "Gerente",
                            Salario = 35000.00m,
                            Telefono = "555-0103"
                        });
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaAgregado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique();

                    b.ToTable("Favorites");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FechaAgregado = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            FechaAgregado = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 2,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("pendiente");

                    b.Property<DateTime>("FechaEmision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Impuestos")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("MetodoPago")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("NumeroFactura")
                        .IsUnique();

                    b.HasIndex("OrderId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.MovimientoInventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Producto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Responsable")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Fecha")
                        .IsDescending();

                    b.HasIndex("Tipo");

                    b.ToTable("MovimientosInventario");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cantidad = 20,
                            Fecha = new DateTime(2026, 7, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Producto = "Lentes Ray-Ban Aviator",
                            Responsable = "Ana Martínez",
                            Tipo = "entrada"
                        },
                        new
                        {
                            Id = 2,
                            Cantidad = 5,
                            Fecha = new DateTime(2026, 7, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Producto = "Lentes de Contacto Acuvue",
                            Responsable = "Juan Pérez",
                            Tipo = "salida"
                        },
                        new
                        {
                            Id = 3,
                            Cantidad = 10,
                            Fecha = new DateTime(2026, 7, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Producto = "Montura Oakley Sport",
                            Responsable = "Ana Martínez",
                            Tipo = "entrada"
                        },
                        new
                        {
                            Id = 4,
                            Cantidad = 15,
                            Fecha = new DateTime(2026, 7, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Producto = "Estuche Premium",
                            Responsable = "Juan Pérez",
                            Tipo = "salida"
                        },
                        new
                        {
                            Id = 5,
                            Cantidad = 50,
                            Fecha = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Producto = "Líquido Limpiador",
                            Responsable = "Ana Martínez",
                            Tipo = "entrada"
                        });
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DireccionEnvio")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("pendiente");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaPedido")
                        .IsDescending();

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DireccionEnvio = "Calle 123 #45-67",
                            Estado = "entregado",
                            FechaPedido = new DateTime(2026, 5, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            Total = 2500.00m,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            DireccionEnvio = "Calle 123 #45-67",
                            Estado = "enviado",
                            FechaPedido = new DateTime(2026, 5, 20, 14, 30, 0, 0, DateTimeKind.Utc),
                            Total = 1800.00m,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cantidad = 1,
                            OrderId = 1,
                            PrecioUnitario = 2500.00m,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            Cantidad = 1,
                            OrderId = 2,
                            PrecioUnitario = 1800.00m,
                            ProductId = 3
                        });
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("EsDestacado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Marca")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("PrecioDescuento")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(3,2)")
                        .HasDefaultValue(4.8m);

                    b.Property<int>("ReviewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(12);

                    b.Property<int>("Stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("Activo");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("EsDestacado");

                    b.HasIndex("Nombre");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            CategoriaId = 1,
                            Descripcion = "Lentes de sol clásicos estilo aviador",
                            EsDestacado = true,
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImagenUrl = "https://images.unsplash.com/photo-1572635196237-14b3f281503f",
                            Marca = "Ray-Ban",
                            Nombre = "Lentes Ray-Ban Aviator",
                            Precio = 2500.00m,
                            Rating = 4.9m,
                            ReviewCount = 28,
                            Stock = 50
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            CategoriaId = 2,
                            Descripcion = "Lentes de contacto mensuales",
                            EsDestacado = true,
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Marca = "Acuvue",
                            Nombre = "Lentes de Contacto Acuvue",
                            Precio = 450.00m,
                            PrecioDescuento = 399.00m,
                            Rating = 4.7m,
                            ReviewCount = 42,
                            Stock = 100
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            CategoriaId = 1,
                            Descripcion = "Montura deportiva ultraligera",
                            EsDestacado = true,
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Marca = "Oakley",
                            Nombre = "Montura Oakley Sport",
                            Precio = 1800.00m,
                            Rating = 4.8m,
                            ReviewCount = 15,
                            Stock = 30
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            CategoriaId = 2,
                            Descripcion = "Lentes graduados con diseño clásico",
                            EsDestacado = true,
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Marca = "LentSoft",
                            Nombre = "Lentes Graduados Classic",
                            Precio = 1200.00m,
                            Rating = 4.6m,
                            ReviewCount = 19,
                            Stock = 40
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            CategoriaId = 3,
                            Descripcion = "Estuche rígido para lentes",
                            EsDestacado = false,
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Marca = "LentSoft",
                            Nombre = "Estuche Premium",
                            Precio = 150.00m,
                            PrecioDescuento = 99.00m,
                            Rating = 4.5m,
                            ReviewCount = 8,
                            Stock = 200
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            CategoriaId = 3,
                            Descripcion = "Solución limpiadora para lentes 360ml",
                            EsDestacado = false,
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Marca = "Opti-Free",
                            Nombre = "Líquido Limpiador",
                            Precio = 120.00m,
                            Rating = 4.9m,
                            ReviewCount = 33,
                            Stock = 150
                        });
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contacto")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("activo");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TipoProducto")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre");

                    b.ToTable("Proveedores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Contacto = "Carlos Ruiz",
                            Email = "ventas@opticaglobal.com",
                            Estado = "activo",
                            FechaRegistro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Óptica Global S.A.",
                            Telefono = "555-1001",
                            TipoProducto = "Monturas"
                        },
                        new
                        {
                            Id = 2,
                            Contacto = "Ana López",
                            Email = "contacto@lenstech.co",
                            Estado = "activo",
                            FechaRegistro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "LensTech Colombia",
                            Telefono = "555-1002",
                            TipoProducto = "Lentes de contacto"
                        },
                        new
                        {
                            Id = 3,
                            Contacto = "Pedro Gómez",
                            Email = "info@distvisual.com",
                            Estado = "activo",
                            FechaRegistro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Distribuidora Visual",
                            Telefono = "555-1003",
                            TipoProducto = "Accesorios"
                        },
                        new
                        {
                            Id = 4,
                            Contacto = "María Fernández",
                            Email = "dist@rayban.co",
                            Estado = "activo",
                            FechaRegistro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Ray-Ban Distribuidor",
                            Telefono = "555-1004",
                            TipoProducto = "Lentes de sol"
                        },
                        new
                        {
                            Id = 5,
                            Contacto = "José Martínez",
                            Email = "partner@oakley.co",
                            Estado = "inactivo",
                            FechaRegistro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Oakley Partner",
                            Telefono = "555-1005",
                            TipoProducto = "Monturas deportivas"
                        });
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("usuario");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("CC");

                    b.Property<DateTime?>("UltimaCompra")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NumeroDocumento")
                        .IsUnique();

                    b.HasIndex("Role");

                    b.ToTable("Users", t =>
                        {
                            t.HasCheckConstraint("CK_Users_Role", "[Role] IN ('usuario', 'admin', 'optometra', 'ventas')");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Sistema",
                            Email = "admin@lentsoft.com",
                            FechaRegistro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Administrador",
                            NumeroDocumento = "1000000001",
                            PasswordHash = "$2a$11$MJPUqK7jAM6tEvUkExo1cO/3cmh4MpxnXNVPg./4kKzlsqAwPW/oq",
                            Role = "admin",
                            TipoDocumento = "CC"
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "Demo",
                            Email = "user@lentsoft.com",
                            FechaRegistro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Usuario",
                            NumeroDocumento = "1000000002",
                            PasswordHash = "$2a$11$q43GcbtmtTn9FyysOC73SO4HUFfBAF43GzPuZ6y0d0EZeDitCKqGa",
                            Role = "usuario",
                            TipoDocumento = "CC"
                        },
                        new
                        {
                            Id = 3,
                            Apellido = "García",
                            Email = "optometra@lentsoft.com",
                            FechaRegistro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "María",
                            NumeroDocumento = "1000000003",
                            PasswordHash = "$2a$11$MJPUqK7jAM6tEvUkExo1cO/3cmh4MpxnXNVPg./4kKzlsqAwPW/oq",
                            Role = "optometra",
                            TipoDocumento = "CC"
                        },
                        new
                        {
                            Id = 4,
                            Apellido = "Pérez",
                            Email = "ventas@lentsoft.com",
                            FechaRegistro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Juan",
                            NumeroDocumento = "1000000004",
                            PasswordHash = "$2a$11$MJPUqK7jAM6tEvUkExo1cO/3cmh4MpxnXNVPg./4kKzlsqAwPW/oq",
                            Role = "ventas",
                            TipoDocumento = "CC"
                        });
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.Appointment", b =>
                {
                    b.HasOne("LentSoft.Web.Models.Entities.User", "User")
                        .WithMany("Appointments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.Favorite", b =>
                {
                    b.HasOne("LentSoft.Web.Models.Entities.Product", "Product")
                        .WithMany("Favorites")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LentSoft.Web.Models.Entities.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.Invoice", b =>
                {
                    b.HasOne("LentSoft.Web.Models.Entities.Order", "Order")
                        .WithMany("Invoices")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.Order", b =>
                {
                    b.HasOne("LentSoft.Web.Models.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.OrderItem", b =>
                {
                    b.HasOne("LentSoft.Web.Models.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LentSoft.Web.Models.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.Product", b =>
                {
                    b.HasOne("LentSoft.Web.Models.Entities.Categoria", "Categoria")
                        .WithMany("Products")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.Categoria", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.Order", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.Product", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.User", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Favorites");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
