// <auto-generated />
using System;
using LentSoft.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LentSoft.Web.Migrations
{
    [DbContext(typeof(LentSoftDbContext))]
    partial class LentSoftDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LentSoft.Web.Models.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("pendiente");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("OptometraId")
                        .HasColumnType("int");

                    b.Property<string>("Servicio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VecesReprogramada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaHora");

                    b.HasIndex("OptometraId");

                    b.HasIndex("UserId");

                    b.ToTable("Appointments", t =>
                        {
                            t.HasTrigger("trg_Appointment_Auditoria");

                            t.HasTrigger("trg_Appointment_PreventOverlap");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Estado = "confirmada",
                            FechaCreacion = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaHora = new DateTime(2026, 5, 25, 10, 0, 0, 0, DateTimeKind.Utc),
                            OptometraId = 3,
                            Servicio = "Examen de vista",
                            UserId = 2,
                            VecesReprogramada = 0
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Estado = "pendiente",
                            FechaCreacion = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            FechaHora = new DateTime(2026, 6, 2, 14, 30, 0, 0, DateTimeKind.Utc),
                            OptometraId = 3,
                            Servicio = "Ajuste de lentes",
                            UserId = 2,
                            VecesReprogramada = 0
                        });
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.AuditoriaCita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<string>("EstadoAnterior")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EstadoNuevo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaCambio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("FechaCambio")
                        .IsDescending();

                    b.ToTable("AuditoriaCitas");
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaContratacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Puesto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Salario")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Activo");

                    b.HasIndex("Departamento");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Departamento = "Atención al Cliente",
                            Email = "maria.garcia@lentsoft.com",
                            FechaContratacion = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "María García",
                            Puesto = "Optometrista",
                            Rol = "Trabajador",
                            Salario = 2500000.00m,
                            Telefono = "555-0101"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Departamento = "Ventas",
                            Email = "juan.perez@lentsoft.com",
                            FechaContratacion = new DateTime(2025, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Juan Pérez",
                            Puesto = "Vendedor",
                            Rol = "Trabajador",
                            Salario = 1800000.00m,
                            Telefono = "555-0102"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Departamento = "Administración",
                            Email = "carlos.mendoza@lentsoft.com",
                            FechaContratacion = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Carlos Mendoza",
                            Puesto = "Gerente",
                            Rol = "Trabajador",
                            Salario = 3500000.00m,
                            Telefono = "555-0103"
                        });
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.ExamenVisual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("AdicionOD")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AdicionOI")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CilindroOD")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CilindroOI")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Diagnostico")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("EjeOD")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EjeOI")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EsferaOD")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EsferaOI")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("OjoDerecho")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OjoIzquierdo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OptometraId")
                        .HasColumnType("int");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SegmentoAnterior")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SegmentoPosterior")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TipoExamen")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TonometriaOD")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TonometriaOI")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Tratamiento")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OptometraId");

                    b.HasIndex("UserId");

                    b.ToTable("ExamenesVisuales");
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaAgregado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique();

                    b.ToTable("Favorites");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FechaAgregado = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            FechaAgregado = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 2,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.FormulaOptica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CilindroOD")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CilindroOI")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DistanciaPupilar")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EjeOD")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EjeOI")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EsferaOD")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EsferaOI")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("OptometraId")
                        .HasColumnType("int");

                    b.Property<string>("TipoLente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OptometraId");

                    b.HasIndex("UserId");

                    b.ToTable("FormulasOpticas");
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.HistorialClinico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Antecedentes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Diagnostico")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ExamenesRealizados")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("OptometraId")
                        .HasColumnType("int");

                    b.Property<string>("Tratamiento")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OptometraId");

                    b.HasIndex("UserId");

                    b.ToTable("HistorialesClinicos", t =>
                        {
                            t.HasTrigger("trg_HistorialClinico_PrevenirEliminacionConFormula");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.InventoryMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Responsable")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Fecha")
                        .IsDescending();

                    b.HasIndex("ProductId");

                    b.ToTable("InventoryMovements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cantidad = 20,
                            Fecha = new DateTime(2026, 5, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 1,
                            Responsable = "Administrador",
                            Tipo = "Entrada"
                        },
                        new
                        {
                            Id = 2,
                            Cantidad = 5,
                            Fecha = new DateTime(2026, 5, 2, 14, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 2,
                            Responsable = "Administrador",
                            Tipo = "Salida"
                        },
                        new
                        {
                            Id = 3,
                            Cantidad = 10,
                            Fecha = new DateTime(2026, 5, 3, 11, 30, 0, 0, DateTimeKind.Utc),
                            ProductId = 3,
                            Responsable = "Administrador",
                            Tipo = "Entrada"
                        });
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("pendiente");

                    b.Property<DateTime>("FechaEmision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Impuestos")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("MetodoPago")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("NumeroFactura")
                        .IsUnique();

                    b.HasIndex("OrderId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("DireccionEnvio")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("pendiente");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("MetodoPagoSimulado")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaPedido")
                        .IsDescending();

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            DireccionEnvio = "Calle 123 #45-67",
                            Estado = "entregado",
                            FechaPedido = new DateTime(2026, 5, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            Total = 2500000.00m,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            DireccionEnvio = "Calle 123 #45-67",
                            Estado = "enviado",
                            FechaPedido = new DateTime(2026, 5, 20, 14, 30, 0, 0, DateTimeKind.Utc),
                            Total = 1800000.00m,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cantidad = 1,
                            OrderId = 1,
                            PrecioUnitario = 2500000.00m,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            Cantidad = 1,
                            OrderId = 2,
                            PrecioUnitario = 1800000.00m,
                            ProductId = 3
                        });
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Color")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("EsDestacado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Estilo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("ImagenOverlayUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Marca")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Material")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("PorcentajeIva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(19.00m);

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("PrecioDescuento")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Proteccion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(3,2)")
                        .HasDefaultValue(4.8m);

                    b.Property<int>("ReviewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(12);

                    b.Property<int>("Stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Tamanio")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Activo");

                    b.HasIndex("Categoria");

                    b.HasIndex("EsDestacado");

                    b.HasIndex("Nombre");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Categoria = "lentes-sol",
                            Color = "Negro / Verde G-15",
                            Descripcion = "Lentes de sol clásicos estilo aviador",
                            EsDestacado = true,
                            Estilo = "Aviador",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImagenOverlayUrl = "/img/overlays/rayban_aviator.svg",
                            ImagenUrl = "https://images.unsplash.com/photo-1572635196237-14b3f281503f",
                            Marca = "Ray-Ban",
                            Material = "Metal",
                            Nombre = "Lentes Ray-Ban Aviator",
                            PorcentajeIva = 19.00m,
                            Precio = 2500000.00m,
                            Proteccion = "UV400",
                            Rating = 4.9m,
                            ReviewCount = 28,
                            Stock = 50,
                            Tamanio = "58-14-135"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Categoria = "lentes-contacto",
                            Descripcion = "Lentes de contacto mensuales",
                            EsDestacado = true,
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Marca = "Acuvue",
                            Nombre = "Lentes de Contacto Acuvue",
                            PorcentajeIva = 19.00m,
                            Precio = 450000.00m,
                            PrecioDescuento = 399000.00m,
                            Rating = 4.7m,
                            ReviewCount = 42,
                            Stock = 100
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Categoria = "monturas",
                            Color = "Negro Mate",
                            Descripcion = "Montura deportiva ultraligera",
                            EsDestacado = true,
                            Estilo = "Deportivo",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImagenOverlayUrl = "/img/overlays/oakley_sport.svg",
                            Marca = "Oakley",
                            Material = "O-Matter (Plástico)",
                            Nombre = "Montura Oakley Sport",
                            PorcentajeIva = 19.00m,
                            Precio = 1800000.00m,
                            Proteccion = "Filtro UV",
                            Rating = 4.8m,
                            ReviewCount = 15,
                            Stock = 30,
                            Tamanio = "55-18-140"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Categoria = "lentes-graduados",
                            Color = "Carey",
                            Descripcion = "Lentes graduados con diseño clásico",
                            EsDestacado = true,
                            Estilo = "Wayfarer",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImagenOverlayUrl = "/img/overlays/classic.svg",
                            Marca = "LentSoft",
                            Material = "Acetato",
                            Nombre = "Lentes Graduados Classic",
                            PorcentajeIva = 19.00m,
                            Precio = 1200000.00m,
                            Proteccion = "Antirreflejo / Luz Azul",
                            Rating = 4.6m,
                            ReviewCount = 19,
                            Stock = 40,
                            Tamanio = "52-19-145"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Categoria = "accesorios",
                            Descripcion = "Estuche rígido para lentes",
                            EsDestacado = false,
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Marca = "LentSoft",
                            Nombre = "Estuche Premium",
                            PorcentajeIva = 19.00m,
                            Precio = 150000.00m,
                            PrecioDescuento = 99000.00m,
                            Rating = 4.5m,
                            ReviewCount = 8,
                            Stock = 200
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Categoria = "accesorios",
                            Descripcion = "Solución limpiadora para lentes 360ml",
                            EsDestacado = false,
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Marca = "Opti-Free",
                            Nombre = "Líquido Limpiador",
                            PorcentajeIva = 5.00m,
                            Precio = 120000.00m,
                            Rating = 4.9m,
                            ReviewCount = 33,
                            Stock = 150
                        });
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.SalesOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("ClienteNombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NumeroPedido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ProductoNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("NumeroPedido");

                    b.ToTable("SalesOrders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Cantidad = 2,
                            ClienteNombre = "Carlos Ramírez",
                            Estado = "entregado",
                            Fecha = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            NumeroPedido = "PED-VENTA-001",
                            PrecioUnitario = 350000.00m,
                            ProductoNombre = "Gafas de Sol Polarizadas Especiales",
                            Total = 700000.00m
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Cantidad = 1,
                            ClienteNombre = "Ana María Torres",
                            Estado = "enviado",
                            Fecha = new DateTime(2026, 5, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            NumeroPedido = "PED-VENTA-002",
                            PrecioUnitario = 480000.00m,
                            ProductoNombre = "Lentes de Contacto Toricos Custom",
                            Total = 480000.00m
                        });
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.Supplier", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TipoProductos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Activo");

                    b.HasIndex("Nombre");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = "PROV001",
                            Activo = true,
                            Correo = "ventas@opticaglobal.com",
                            FechaRegistro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Óptica Global S.A.",
                            Telefono = "555-1001",
                            TipoProductos = "Monturas"
                        },
                        new
                        {
                            Id = "PROV002",
                            Activo = true,
                            Correo = "contacto@lenstech.co",
                            FechaRegistro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "LensTech Colombia",
                            Telefono = "555-1002",
                            TipoProductos = "Lentes de contacto"
                        },
                        new
                        {
                            Id = "PROV003",
                            Activo = true,
                            Correo = "info@distvisual.com",
                            FechaRegistro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Distribuidora Visual",
                            Telefono = "555-1003",
                            TipoProductos = "Accesorios"
                        });
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.SupplierOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NumeroPedido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("SupplierId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("NumeroPedido");

                    b.HasIndex("ProductId");

                    b.HasIndex("SupplierId");

                    b.ToTable("SupplierOrders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Cantidad = 15,
                            Estado = "recibido",
                            Fecha = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            NumeroPedido = "PED-PROV-001",
                            PrecioUnitario = 1200000.00m,
                            ProductId = 1,
                            SupplierId = "PROV001",
                            Total = 18000000.00m
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Cantidad = 30,
                            Estado = "pendiente",
                            Fecha = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            NumeroPedido = "PED-PROV-002",
                            PrecioUnitario = 200000.00m,
                            ProductId = 2,
                            SupplierId = "PROV002",
                            Total = 6000000.00m
                        });
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int?>("AniosExperiencia")
                        .HasColumnType("int");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("EPS")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EspecialidadDetalle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EstadoPaciente")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Genero")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ObservacionesPaciente")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RegistroMedico")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("usuario");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("CC");

                    b.Property<DateTime?>("UltimaCompra")
                        .HasColumnType("datetime2");

                    b.Property<string>("Universidad")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NumeroDocumento")
                        .IsUnique();

                    b.HasIndex("Role");

                    b.ToTable("Users", t =>
                        {
                            t.HasCheckConstraint("CK_Users_Role", "[Role] IN ('usuario', 'admin', 'optometra', 'ventas')");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Apellido = "Sistema",
                            Email = "admin@lentsoft.com",
                            EstadoPaciente = "Activo",
                            FechaRegistro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Administrador",
                            NumeroDocumento = "1000000001",
                            PasswordHash = "$2a$11$MJPUqK7jAM6tEvUkExo1cO/3cmh4MpxnXNVPg./4kKzlsqAwPW/oq",
                            Role = "admin",
                            TipoDocumento = "CC"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Apellido = "Demo",
                            Email = "user@lentsoft.com",
                            EstadoPaciente = "Activo",
                            FechaRegistro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Usuario",
                            NumeroDocumento = "1000000002",
                            PasswordHash = "$2a$11$q43GcbtmtTn9FyysOC73SO4HUFfBAF43GzPuZ6y0d0EZeDitCKqGa",
                            Role = "usuario",
                            TipoDocumento = "CC"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Apellido = "García",
                            Email = "optometra@lentsoft.com",
                            EstadoPaciente = "Activo",
                            FechaRegistro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "María",
                            NumeroDocumento = "1000000003",
                            PasswordHash = "$2a$11$MJPUqK7jAM6tEvUkExo1cO/3cmh4MpxnXNVPg./4kKzlsqAwPW/oq",
                            Role = "optometra",
                            TipoDocumento = "CC"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Apellido = "Pérez",
                            Email = "ventas@lentsoft.com",
                            EstadoPaciente = "Activo",
                            FechaRegistro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Juan",
                            NumeroDocumento = "1000000004",
                            PasswordHash = "$2a$11$MJPUqK7jAM6tEvUkExo1cO/3cmh4MpxnXNVPg./4kKzlsqAwPW/oq",
                            Role = "ventas",
                            TipoDocumento = "CC"
                        });
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.Appointment", b =>
                {
                    b.HasOne("LentSoft.Web.Models.Entities.User", "Optometra")
                        .WithMany()
                        .HasForeignKey("OptometraId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("LentSoft.Web.Models.Entities.User", "User")
                        .WithMany("Appointments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Optometra");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.AuditoriaCita", b =>
                {
                    b.HasOne("LentSoft.Web.Models.Entities.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.Cart", b =>
                {
                    b.HasOne("LentSoft.Web.Models.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("LentSoft.Web.Models.Entities.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.CartItem", b =>
                {
                    b.HasOne("LentSoft.Web.Models.Entities.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LentSoft.Web.Models.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.ExamenVisual", b =>
                {
                    b.HasOne("LentSoft.Web.Models.Entities.User", "Optometra")
                        .WithMany()
                        .HasForeignKey("OptometraId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LentSoft.Web.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Optometra");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.Favorite", b =>
                {
                    b.HasOne("LentSoft.Web.Models.Entities.Product", "Product")
                        .WithMany("Favorites")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LentSoft.Web.Models.Entities.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.FormulaOptica", b =>
                {
                    b.HasOne("LentSoft.Web.Models.Entities.User", "Optometra")
                        .WithMany()
                        .HasForeignKey("OptometraId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LentSoft.Web.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Optometra");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.HistorialClinico", b =>
                {
                    b.HasOne("LentSoft.Web.Models.Entities.User", "Optometra")
                        .WithMany()
                        .HasForeignKey("OptometraId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LentSoft.Web.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Optometra");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.InventoryMovement", b =>
                {
                    b.HasOne("LentSoft.Web.Models.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.Invoice", b =>
                {
                    b.HasOne("LentSoft.Web.Models.Entities.Order", "Order")
                        .WithMany("Invoices")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.Order", b =>
                {
                    b.HasOne("LentSoft.Web.Models.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.OrderItem", b =>
                {
                    b.HasOne("LentSoft.Web.Models.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LentSoft.Web.Models.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.SupplierOrder", b =>
                {
                    b.HasOne("LentSoft.Web.Models.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LentSoft.Web.Models.Entities.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.Order", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.Product", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("LentSoft.Web.Models.Entities.User", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Favorites");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
